# Site settings
title: yuweijun's Blog
email: test.yu@gmail.com
description: "{\"type\":\"编程笔记\"}"
baseurl: "/blog"
url: "http://yuweijun.github.io"
twitter_username: yuweijun
github_username: yuweijun

# Build settings
markdown: kramdown
permalink: pretty
