# Site settings
title: yuweijun's Blog
email: test.yu@gmail.com
description: '{"select": "jQuery", "from": "javascript libraries"}'
baseurl: "/blog"
url: "http://yuweijun.github.io/blog/"
twitter_username: yuweijun
github_username: yuweijun

# Build settings
markdown: kramdown
permalink: pretty
