# Site settings
title: yuweijun's blog
email: yuweijun@live.com
description: "{\"type\":\"编程笔记\"}"
baseurl: "/blog"
url: "http://www.4e00.com"
twitter_username: yuweijun
github_username: yuweijun

# Build settings
markdown: kramdown
incremental: true
paginate: 50
gems: [jekyll-paginate]
# turn off smart-quotes for both apostrophes/single-quotes and double quotes
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
