# Site settings
title: yuweijun's blog
email: yuweijun@live.com
description: "{\"type\":\"编程笔记\"}"
baseurl: "/blog"
url: "http://yuweijun.github.io"
twitter_username: yuweijun
github_username: yuweijun

# Build settings
markdown: kramdown
paginate: 15
gems: [jekyll-paginate]
