# Site settings
title: yuweijun's blog
email: yuweijun@live.com
description: "{\"type\":\"编程笔记\"}"
baseurl: "/blog"
url: "http://www.4e00.com"
twitter_username: yuweijun
github_username: yuweijun

# Build settings
markdown: kramdown
paginate: 26
gems: [jekyll-paginate]
